# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0gv6cp7cvg54dq0qy7y6hhjsvp16w1fq602dl0dl0vfcg2hd2cb4";
    aarch64-linux = "0rcz0xbwl7papvp00lb1wbqcfbwkcklw6jbqkyiywncsa56h4bfq";
  };

  urlMap = {
    x86_64-linux = "https://github.com/wimpysworld/WonKey/releases/download/v0.1.1/WonKey_0.1.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/wimpysworld/WonKey/releases/download/v0.1.1/WonKey_0.1.1_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "wonkey";
  version = "0.1.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./wonkey $out/bin/wonkey
  '';

  meta = {
    description = "Configure your XFKEY One Key Max on Linux.";
    homepage = "https://github.com/wimpysworld/WonKey";
    license = lib.licenses.blueOak100;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
