# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1isg2n6cx3f3knjjyb0fxgvrbmynnnivxr2fa8knwm1mqsb62xia";
    aarch64-linux = "0pzn9mkzzrnmh6kv8k7x5yi5w058m7kj0w12ayzfsffdi2466jbf";
    x86_64-darwin = "0yip79bnr3k6ywllgzjf5lcgvhbd6b297y7qvh56a79jf10d8n8x";
    aarch64-darwin = "1py2pc8m2siir8r8g5asygyfvb7zwyfb0blna4x0kbzgk435c34b";
  };

  urlMap = {
    x86_64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.1.2/tailor_0.1.2_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.1.2/tailor_0.1.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.1.2/tailor_0.1.2_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.1.2/tailor_0.1.2_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tailor";
  version = "0.1.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tailor $out/bin/tailor
  '';

  meta = {
    description = "Ready-to-wear project templates for GitHub repositories.";
    homepage = "https://github.com/wimpysworld/tailor";
    license = lib.licenses.blueOak100;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
