# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1vpwvb5nz90a6v7qba2s0jb2pqyhz187z8j5q7ygby1s7qhpcab0";
    aarch64-linux = "03nkhh36jcphw0jdscjrxhcshdf1v1bxjxlmzb472n95fyw4b2v3";
    x86_64-darwin = "1j09sfg7zxclz9m50gz10mlgq9bc2f8zmrz8dmw7rajb72a1rsva";
    aarch64-darwin = "0f89ql1vqpx30yqph6s67xhs4cp26d6jca5ahghzj0jzkfhmccam";
  };

  urlMap = {
    x86_64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.3.0/tailor_0.3.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.3.0/tailor_0.3.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.3.0/tailor_0.3.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.3.0/tailor_0.3.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tailor";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tailor $out/bin/tailor
  '';

  meta = {
    description = "Ready-to-wear project templates for GitHub repositories.";
    homepage = "https://github.com/wimpysworld/tailor";
    license = lib.licenses.blueOak100;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
