# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0h8hgdlaas1gxzmpnqcbhpcvb94idgmcrcpfwnn1vl023iza9yzi";
    aarch64-linux = "0g751zyyls5dksd7j8jda7msbrqfci2l88p22n433lzgmw4x3gwg";
    x86_64-darwin = "1mjc1h0ab45lf00xibm8rb52p7lg4hfprv97zjq6jw5xqy41b906";
    aarch64-darwin = "1ryaj3xxcba3snvfrx9ld2cvjywg10zqcclg5rsfc1wppbp8hghd";
  };

  urlMap = {
    x86_64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.2.1/tailor_0.2.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/wimpysworld/tailor/releases/download/v0.2.1/tailor_0.2.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.2.1/tailor_0.2.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/wimpysworld/tailor/releases/download/v0.2.1/tailor_0.2.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tailor";
  version = "0.2.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tailor $out/bin/tailor
  '';

  meta = {
    description = "Ready-to-wear project templates for GitHub repositories.";
    homepage = "https://github.com/wimpysworld/tailor";
    license = lib.licenses.blueOak100;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
